name = "cosepo"
version = "0.0.2"
description = "A module for parsing, mutating, and serializing Content-Security-Policy directives."
repository = { type = "github", user = "jshawl", repo = "cosepo" }
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
